/**
 * Pipeline Planner — Calls Claude Opus headless to generate intelligent execution plans.
 *
 * Instead of keyword heuristics, this planner sends all context (instructions,
 * documents, available agents/skills catalog) to Claude Opus which produces
 * a structured JSON plan with waves, steps, sprints, and scoped prompts.
 *
 * @module pipeline/planner
 */

import type {
  PipelinePlan,
  PipelineInput,
  PipelineConstraints,
} from "./types";
import { generateId, truncate } from "../lib/helpers";
import { createLogger } from "../lib/logger";

const log = createLogger("Planner");

// ============================================
// Constants
// ============================================

/** Maximum chars per document to include in the planner prompt */
const MAX_DOC_CHARS = 4000;

/** Timeout for the headless claude call (10 minutes — Opus is slow on large prompts) */
const PLANNER_TIMEOUT_MS = 600_000;

/** Path to the skill-index for agent/skill reference */
const SKILL_INDEX_PATH = new URL(
  "../../hooks/skill-advisor/skill-index.json",
  import.meta.url,
).pathname;

// ============================================
// Main Entry Point
// ============================================

/**
 * Generate a complete execution plan by calling Claude Opus headless.
 *
 * Sends all context (instructions, documents, available agents/skills)
 * to Claude Opus which analyzes and produces a structured JSON plan
 * with as many waves and sprints as it deems necessary.
 *
 * @param input - User instructions, documents, and scope targets
 * @param _sessionId - Active session identifier
 * @returns A fully-formed PipelinePlan ready for execution
 */
export async function generatePlan(
  input: PipelineInput,
  _sessionId: string,
): Promise<PipelinePlan> {
  const startMs = performance.now();
  log.info("Generating plan via Claude Opus headless...");

  // 1. Load available agents/skills catalog
  const catalog = await loadCatalogReference();

  // 2. Build the mega-prompt
  const prompt = buildPlannerPrompt(input, catalog);

  // 3. Call Claude Opus headless
  const rawOutput = await callClaudeHeadless(prompt);

  // 4. Parse the JSON response
  const plan = parsePlanOutput(rawOutput, input);

  const elapsed = Math.round(performance.now() - startMs);
  log.info(
    `Plan generated by Opus: id=${plan.plan_id}, waves=${plan.waves.length}, ` +
    `sprints=${plan.sprints.length}, steps=${plan.waves.reduce((s, w) => s + w.steps.length, 0)}, ` +
    `took=${elapsed}ms`,
  );

  return plan;
}

// ============================================
// Claude Headless Call
// ============================================

/**
 * Call Claude CLI headless in a fully detached process.
 *
 * Writes prompt to a temp file, launches a shell script that runs
 * `claude --print` and writes output to another temp file, then
 * polls for the result file using non-blocking setInterval.
 * This ensures the Bun event loop is NEVER blocked — the API server
 * stays responsive and systemd watchdog is satisfied.
 */
async function callClaudeHeadless(prompt: string): Promise<string> {
  const { writeFile, readFile, unlink } = await import("node:fs/promises");
  const { randomUUID } = await import("node:crypto");

  const jobId = randomUUID().slice(0, 8);
  const tmpDir = "/tmp/dcm-planner";
  await Bun.spawn(["mkdir", "-p", tmpDir]).exited;

  const promptFile = `${tmpDir}/${jobId}.prompt`;
  const outputFile = `${tmpDir}/${jobId}.output`;
  const errorFile = `${tmpDir}/${jobId}.error`;
  const doneFile = `${tmpDir}/${jobId}.done`;

  // Write prompt to file
  await writeFile(promptFile, prompt, "utf-8");

  log.info(`Planner job ${jobId}: launching detached claude process (prompt: ${prompt.length} chars)`);

  // Launch in a separate systemd scope so it survives service restarts.
  // Use --system-prompt-file for the large prompt, -p for the trigger message.
  const claudeCmd = `claude -p "Generate the execution plan now. Output ONLY valid JSON, no markdown." --system-prompt-file "${promptFile}" --model claude-sonnet-4-6 --output-format text > "${outputFile}" 2> "${errorFile}"; echo $? > "${doneFile}"`;
  const proc = Bun.spawn(
    ["systemd-run", "--user", "--scope", "--", "bash", "-c", claudeCmd],
    { stdout: "ignore", stderr: "pipe", stdin: "ignore" },
  );
  // If systemd-run fails (not available), fallback to setsid
  proc.exited.then(async (code) => {
    if (code !== 0) {
      const doneExists = await Bun.file(doneFile).exists();
      if (!doneExists) {
        log.warn(`systemd-run failed (exit ${code}), falling back to setsid`);
        Bun.spawn(["setsid", "bash", "-c", claudeCmd], {
          stdout: "ignore", stderr: "ignore", stdin: "ignore",
        });
      }
    }
  });

  // Poll for completion (non-blocking, 2s interval)
  return new Promise<string>((resolve, reject) => {
    const startTime = Date.now();
    const pollInterval = setInterval(async () => {
      try {
        const doneExists = await Bun.file(doneFile).exists();
        if (!doneExists) {
          // Check timeout
          if (Date.now() - startTime > PLANNER_TIMEOUT_MS) {
            clearInterval(pollInterval);
            log.error(`Planner job ${jobId}: timed out after ${PLANNER_TIMEOUT_MS / 1000}s`);
            cleanup();
            reject(new Error("Planner timed out"));
          }
          return; // Still running — check again in 2s
        }

        clearInterval(pollInterval);

        const exitCode = (await readFile(doneFile, "utf-8")).trim();
        const stdout = await readFile(outputFile, "utf-8").catch(() => "");
        const stderr = await readFile(errorFile, "utf-8").catch(() => "");

        cleanup();

        if (exitCode !== "0") {
          log.error(`Planner job ${jobId}: claude failed (exit ${exitCode}): ${stderr.slice(0, 300)}`);
          reject(new Error(`Planner agent failed: ${stderr.slice(0, 200)}`));
          return;
        }

        if (!stdout.trim()) {
          reject(new Error("Planner agent returned empty output"));
          return;
        }

        log.info(`Planner job ${jobId}: completed, ${stdout.length} chars output`);
        resolve(stdout);
      } catch (error) {
        clearInterval(pollInterval);
        cleanup();
        reject(error);
      }
    }, 2000);

    async function cleanup() {
      for (const f of [promptFile, outputFile, errorFile, doneFile]) {
        await unlink(f).catch(() => {});
      }
    }
  });
}

// ============================================
// Prompt Construction
// ============================================

/**
 * Build the complete prompt that tells Opus what plan to produce.
 */
function buildPlannerPrompt(input: PipelineInput, catalog: string): string {
  const sections: string[] = [];

  sections.push(`Tu es un architecte logiciel expert. Tu dois produire un plan d'execution structure pour un pipeline d'agents AI.

Tu recois des instructions, des documents optionnels, et un catalogue d'agents/skills disponibles.
Tu dois analyser le travail demande et produire un plan JSON detaille avec des waves, des steps, et des sprints.

# IMPORTANT
- Reponds UNIQUEMENT avec un bloc JSON valide (pas de texte avant/apres)
- Le JSON doit etre parsable directement
- Sois exhaustif dans le decoupage : autant de sprints et waves que necessaire
- Chaque step doit avoir un prompt detaille et scope pour l'agent qui l'executera
- Les sprints groupent les waves logiquement (1 sprint = 1 livrable coherent)
- Un sprint peut contenir 1 a N waves`);

  // Instructions
  sections.push(`\n# INSTRUCTIONS DE L'UTILISATEUR\n\n${input.instructions}`);

  // Documents
  if (input.documents && input.documents.length > 0) {
    sections.push("\n# DOCUMENTS FOURNIS\n");
    for (const doc of input.documents) {
      sections.push(`## ${doc.name} (${doc.type})\n\n${truncate(doc.content, MAX_DOC_CHARS)}\n`);
    }
  }

  // Scope
  if (input.target_files && input.target_files.length > 0) {
    sections.push(`\n# FICHIERS CIBLES\n${input.target_files.map(f => `- ${f}`).join("\n")}`);
  }
  if (input.target_directories && input.target_directories.length > 0) {
    sections.push(`\n# DOSSIERS CIBLES\n${input.target_directories.map(d => `- ${d}`).join("\n")}`);
  }

  // Workspace
  if (input.workspace) {
    sections.push(`\n# WORKSPACE\n- Dossier: ${input.workspace.path}`);
    if (input.workspace.git_repo_url) {
      sections.push(`- Git: ${input.workspace.git_repo_url} (branche: ${input.workspace.git_branch ?? "main"})`);
    }
  }

  // Catalog
  sections.push(`\n# CATALOGUE AGENTS & SKILLS DISPONIBLES\n\n${catalog}`);

  // Output schema
  sections.push(`\n# FORMAT DE SORTIE ATTENDU

Produis EXACTEMENT ce JSON (pas de markdown, pas de \`\`\`json, juste le JSON brut) :

{
  "name": "Nom court du plan (max 60 chars)",
  "waves": [
    {
      "number": 0,
      "name": "Nom de la wave",
      "steps": [
        {
          "order": 0,
          "agent_type": "type exact de l'agent (du catalogue)",
          "description": "Ce que cet agent doit faire",
          "skills": ["skill-1", "skill-2"],
          "prompt": "Le prompt COMPLET et DETAILLE pour l'agent. Inclure: contexte, objectif precis, fichiers a toucher, contraintes, format de retour attendu. Minimum 200 mots.",
          "model": "haiku|sonnet|opus",
          "max_turns": 5,
          "target_files": [],
          "target_directories": [],
          "retry_strategy": "enhanced",
          "max_retries": 2
        }
      ],
      "depends_on": [],
      "on_failure": "continue|retry|abort"
    }
  ],
  "sprints": [
    {
      "number": 1,
      "name": "Nom du sprint",
      "objectives": ["Objectif 1 precis et mesurable", "Objectif 2"],
      "wave_start": 0,
      "wave_end": 1
    }
  ],
  "required_skills": ["skill-1", "skill-2"],
  "constraints": {
    "max_parallel": 4,
    "max_total_retries": 6,
    "timeout_ms": 0
  }
}

# REGLES POUR LE PLAN

1. **Wave 0 TOUJOURS = Exploration** : un agent Explore qui analyse le codebase et comprend le contexte
2. **Waves d'implementation** : utilise les agents les plus pertinents du catalogue, en parallele quand possible
3. **Wave de validation** : toujours inclure un code-reviewer
4. **Waves optionnelles** : security-specialist, test-engineer, performance-engineer selon le besoin
5. **Sprints** : groupe les waves en livrables coherents. Un sprint = un commit git potentiel. Autant de sprints que necessaire (pas forcement 3).
6. **Modeles** : haiku pour exploration/review simple, sonnet pour implementation, opus pour architecture complexe
7. **max_turns** : 3-5 pour trivial, 5-10 pour simple, 10-20 pour modere, 20-30 pour complexe
8. **Prompts** : DETAILLES et SCOPES. Chaque prompt doit etre autonome — l'agent ne connait PAS le plan global.
9. **Skills** : toujours inclure "workflow-clean-code" + les skills specifiques au domaine de l'agent
10. **Pas de wave vide** : chaque wave doit avoir au moins 1 step`);

  return sections.join("\n");
}

// ============================================
// Output Parsing
// ============================================

/**
 * Parse the raw output from Claude Opus into a validated PipelinePlan.
 * Handles JSON extraction from potentially wrapped output.
 */
function parsePlanOutput(raw: string, input: PipelineInput): PipelinePlan {
  let jsonStr = raw.trim();

  // Strip markdown code fences if present
  const fenceMatch = jsonStr.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
  if (fenceMatch?.[1]) {
    jsonStr = fenceMatch[1].trim();
  }

  // Try to find JSON object boundaries
  const firstBrace = jsonStr.indexOf("{");
  const lastBrace = jsonStr.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace > firstBrace) {
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
  }

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(jsonStr) as Record<string, unknown>;
  } catch (parseError) {
    log.error(`Failed to parse plan JSON: ${(parseError as Error).message}`);
    log.error(`Raw output (first 500 chars): ${raw.slice(0, 500)}`);
    // Fallback to minimal plan
    return buildFallbackPlan(input);
  }

  // Validate required fields
  if (!parsed["waves"] || !Array.isArray(parsed["waves"]) || (parsed["waves"] as unknown[]).length === 0) {
    log.warn("Plan has no waves, using fallback");
    return buildFallbackPlan(input);
  }

  const waves = parsed["waves"] as Array<Record<string, unknown>>;
  const sprints = (parsed["sprints"] as Array<Record<string, unknown>>) ?? [];
  const requiredSkills = (parsed["required_skills"] as string[]) ?? ["workflow-clean-code"];
  const constraints = (parsed["constraints"] as Record<string, unknown>) ?? {};

  // Build validated plan
  const plan: PipelinePlan = {
    plan_id: generateId("plan"),
    version: 1,
    name: String(parsed["name"] ?? buildPlanName(input.instructions)),
    waves: waves.map((w, idx) => ({
      number: Number(w["number"] ?? idx),
      name: String(w["name"] ?? `Wave ${idx}`),
      steps: Array.isArray(w["steps"])
        ? (w["steps"] as Array<Record<string, unknown>>).map((s, sIdx) => ({
            order: Number(s["order"] ?? sIdx),
            agent_type: String(s["agent_type"] ?? "Snipper"),
            description: String(s["description"] ?? ""),
            skills: Array.isArray(s["skills"]) ? (s["skills"] as string[]) : ["workflow-clean-code"],
            prompt: String(s["prompt"] ?? s["description"] ?? ""),
            model: String(s["model"] ?? "sonnet"),
            max_turns: Number(s["max_turns"] ?? 10),
            target_files: Array.isArray(s["target_files"]) ? (s["target_files"] as string[]) : (input.target_files ?? []),
            target_directories: Array.isArray(s["target_directories"]) ? (s["target_directories"] as string[]) : (input.target_directories ?? []),
            retry_strategy: (String(s["retry_strategy"] ?? "enhanced")) as "same" | "enhanced" | "alternate" | "decompose",
            max_retries: Number(s["max_retries"] ?? 2),
          }))
        : [],
      depends_on: Array.isArray(w["depends_on"]) ? (w["depends_on"] as number[]) : (idx > 0 ? [idx - 1] : []),
      on_failure: (String(w["on_failure"] ?? "continue")) as "abort" | "continue" | "retry",
    })),
    sprints: sprints.map((s, idx) => ({
      number: Number(s["number"] ?? idx + 1),
      name: String(s["name"] ?? `Sprint ${idx + 1}`),
      objectives: Array.isArray(s["objectives"]) ? (s["objectives"] as string[]) : [],
      wave_start: Number(s["wave_start"] ?? 0),
      wave_end: Number(s["wave_end"] ?? 0),
    })),
    required_skills: requiredSkills,
    constraints: {
      max_parallel: Number(constraints["max_parallel"] ?? 4),
      max_total_retries: Number(constraints["max_total_retries"] ?? 6),
      timeout_ms: Number(constraints["timeout_ms"] ?? 0),
    },
  };

  // If Opus didn't produce sprints, generate minimal ones
  if (plan.sprints.length === 0 && plan.waves.length > 0) {
    plan.sprints = autoGenerateSprints(plan.waves);
  }

  return plan;
}

// ============================================
// Catalog Loading
// ============================================

/**
 * Load the skill-index.json to give Opus a reference of available agents/skills.
 * Falls back to a minimal list if file not found.
 */
async function loadCatalogReference(): Promise<string> {
  try {
    const file = Bun.file(SKILL_INDEX_PATH);
    if (!(await file.exists())) {
      log.warn(`Skill index not found at ${SKILL_INDEX_PATH}, using minimal catalog`);
      return getMinimalCatalog();
    }

    const raw = await file.text();
    const index = JSON.parse(raw) as Record<string, unknown>;
    const domains = index["domains"] as Record<string, Record<string, unknown>> | undefined;

    if (!domains) return getMinimalCatalog();

    // Build a concise summary for the planner
    const lines: string[] = [];
    for (const [domain, info] of Object.entries(domains)) {
      const agents = (info["agents"] as Record<string, string[]>)?.["recommended"] ?? [];
      const skills = (info["primary"] as string[]) ?? [];
      const keywords = (info["keywords"] as string[]) ?? [];
      lines.push(`## ${domain}`);
      lines.push(`Agents: ${agents.join(", ")}`);
      lines.push(`Skills: ${skills.join(", ")}`);
      lines.push(`Keywords: ${keywords.slice(0, 8).join(", ")}`);
      lines.push("");
    }

    return lines.join("\n");
  } catch (error) {
    log.warn("Failed to load skill index:", error);
    return getMinimalCatalog();
  }
}

/**
 * Minimal catalog when skill-index.json is not available.
 */
function getMinimalCatalog(): string {
  return `## Agents disponibles
- Explore : exploration et comprehension du codebase (haiku, 5 turns)
- Snipper : modifications de code rapides (sonnet, 10 turns)
- frontend-react : composants React, hooks, state (sonnet, 15 turns)
- backend-laravel : API Laravel, controllers, models (sonnet, 15 turns)
- backend-developer : APIs Node.js/Bun/Hono (sonnet, 15 turns)
- database-admin : schema PostgreSQL, migrations, index (sonnet, 10 turns)
- code-reviewer : revue de code, qualite, bugs (sonnet, 10 turns)
- test-engineer : tests unitaires, integration, e2e (sonnet, 10 turns)
- security-specialist : audit securite, OWASP (sonnet, 15 turns)
- performance-engineer : optimisation, profiling, cache (sonnet, 15 turns)
- designer-ui-ux : design system, accessibilite (sonnet, 15 turns)
- technical-writer : documentation, API docs (haiku, 5 turns)
- devops-infra : CI/CD, Docker, deploy (sonnet, 10 turns)
- qa-testing : QA, tests manuels, validation (haiku, 10 turns)
- impact-analyzer : analyse d'impact avant modification (sonnet, 10 turns)
- regression-guard : validation anti-regression (sonnet, 10 turns)

## Skills disponibles
- workflow-clean-code (toujours requis)
- react-best-practices, vercel-react-best-practices
- laravel-expert, api-design-principles
- postgresql, sql-pro
- senior-qa, tdd-orchestrator
- security-auditor, vulnerability-scanner
- senior-devops, docker-expert
- ui-ux-pro-max, web-design-reviewer
- typescript-expert, senior-architect`;
}

// ============================================
// Fallback Plan
// ============================================

/**
 * Build a minimal fallback plan when Opus fails or returns invalid JSON.
 * Uses the old heuristic approach as safety net.
 */
function buildFallbackPlan(input: PipelineInput): PipelinePlan {
  log.warn("Using fallback heuristic plan (Opus failed to produce valid JSON)");

  const plan: PipelinePlan = {
    plan_id: generateId("plan"),
    version: 1,
    name: buildPlanName(input.instructions),
    waves: [
      {
        number: 0,
        name: "Exploration",
        steps: [{
          order: 0,
          agent_type: "Explore",
          description: "Explore and understand the codebase",
          skills: ["workflow-clean-code"],
          prompt: `# Exploration\n\nAnalyze the codebase to understand:\n${input.instructions}\n\nProvide a summary of relevant files, patterns, and dependencies.`,
          model: "haiku",
          max_turns: 5,
          target_files: input.target_files ?? [],
          target_directories: input.target_directories ?? [],
          retry_strategy: "enhanced",
          max_retries: 2,
        }],
        depends_on: [],
        on_failure: "continue",
      },
      {
        number: 1,
        name: "Implementation",
        steps: [{
          order: 0,
          agent_type: "Snipper",
          description: `Implement: ${truncate(input.instructions, 120)}`,
          skills: ["workflow-clean-code"],
          prompt: `# Implementation\n\n${input.instructions}\n\nImplement the changes described above.`,
          model: "sonnet",
          max_turns: 15,
          target_files: input.target_files ?? [],
          target_directories: input.target_directories ?? [],
          retry_strategy: "enhanced",
          max_retries: 2,
        }],
        depends_on: [0],
        on_failure: "retry",
      },
      {
        number: 2,
        name: "Validation",
        steps: [{
          order: 0,
          agent_type: "code-reviewer",
          description: "Review implementation",
          skills: ["workflow-clean-code"],
          prompt: "Review all changes made. Check for bugs, security issues, and code quality.",
          model: "haiku",
          max_turns: 5,
          target_files: input.target_files ?? [],
          target_directories: input.target_directories ?? [],
          retry_strategy: "enhanced",
          max_retries: 1,
        }],
        depends_on: [1],
        on_failure: "continue",
      },
    ],
    sprints: [
      { number: 1, name: "Discovery", objectives: ["Understand the codebase"], wave_start: 0, wave_end: 0 },
      { number: 2, name: "Implementation", objectives: ["Deliver the changes"], wave_start: 1, wave_end: 1 },
      { number: 3, name: "Validation", objectives: ["Ensure quality"], wave_start: 2, wave_end: 2 },
    ],
    required_skills: ["workflow-clean-code"],
    constraints: { max_parallel: 4, max_total_retries: 6, timeout_ms: 0 },
  };

  return plan;
}

// ============================================
// Helpers
// ============================================

/**
 * Auto-generate sprints when Opus doesn't provide them.
 * Groups waves into logical sprints.
 */
function autoGenerateSprints(waves: PipelinePlan["waves"]): PipelinePlan["sprints"] {
  if (waves.length <= 2) {
    return [{ number: 1, name: "Full Pipeline", objectives: waves.map(w => w.name), wave_start: 0, wave_end: waves.length - 1 }];
  }

  return [
    { number: 1, name: "Discovery", objectives: ["Exploration du codebase"], wave_start: 0, wave_end: 0 },
    { number: 2, name: "Implementation", objectives: waves.slice(1, -1).map(w => w.name), wave_start: 1, wave_end: waves.length - 2 },
    { number: 3, name: "Quality", objectives: [waves[waves.length - 1]?.name ?? "Validation"], wave_start: waves.length - 1, wave_end: waves.length - 1 },
  ];
}

function buildPlanName(instructions: string): string {
  const firstLine = instructions.split("\n")[0] ?? instructions;
  const cleaned = firstLine.replace(/[^a-zA-Z0-9\s\u00C0-\u024F-]/g, "").trim();
  return truncate(cleaned, 60) || "Pipeline";
}

// Re-export for backward compat (used by runner tests)
export { buildPlannerPrompt as buildStepPrompt };
