/**
 * Pipeline Types — Shared type definitions for the pipeline engine
 * @module pipeline/types
 */

// ============================================
// Pipeline Status & Enums
// ============================================

export type PipelineStatus =
  | "planning"    // Plan is being generated
  | "ready"       // Plan generated, awaiting start
  | "running"     // Actively executing waves
  | "paused"      // Paused by user or decision engine
  | "completed"   // All waves finished successfully
  | "failed"      // Pipeline failed (unrecoverable)
  | "cancelled";  // Cancelled by user

export type StepStatus =
  | "pending"     // Waiting for wave to start
  | "queued"      // Wave started, step is next
  | "running"     // Agent is executing
  | "completed"   // Agent finished successfully
  | "failed"      // Agent failed
  | "retrying"    // Agent failed, retry in progress
  | "skipped"     // Skipped by decision engine
  | "blocked";    // Blocked by dependency

export type DecisionAction =
  | "proceed"     // Move to next wave
  | "retry"       // Retry failed step with same config
  | "retry_alt"   // Retry with different agent/model
  | "skip"        // Skip failed step, continue pipeline
  | "pause"       // Pause pipeline, wait for user
  | "abort"       // Abort entire pipeline
  | "inject"      // Inject an extra step before continuing
  | "human";      // Escalate to human decision

export type RetryStrategy =
  | "same"        // Same agent, same prompt
  | "enhanced"    // Same agent, enhanced prompt with error context
  | "alternate"   // Different agent type
  | "decompose";  // Break into smaller subtasks

// ============================================
// Pipeline Input
// ============================================

export interface PipelineInput {
  /** Human-readable instructions */
  instructions: string;
  /** Optional documents to process (markdown, text) */
  documents?: PipelineDocument[];
  /** Optional context from previous work */
  context?: Record<string, unknown>;
  /** Target files/directories to scope the work */
  target_files?: string[];
  target_directories?: string[];
}

export interface PipelineDocument {
  name: string;
  content: string;
  type: "markdown" | "text" | "json" | "code";
}

// ============================================
// Pipeline Plan (generated by planner)
// ============================================

export interface PipelinePlan {
  /** Unique plan identifier */
  plan_id: string;
  /** Plan version (incremented on replanning) */
  version: number;
  /** Generated plan name */
  name: string;
  /** Estimated total duration */
  estimated_duration_ms?: number;
  /** Ordered waves of execution */
  waves: PipelineWave[];
  /** Skills required across entire pipeline */
  required_skills: string[];
  /** Global constraints */
  constraints: PipelineConstraints;
}

export interface PipelineWave {
  /** Wave number (0-indexed) */
  number: number;
  /** Human-readable wave name */
  name: string;
  /** Steps within this wave (executed in parallel) */
  steps: PipelineStepDef[];
  /** Dependencies: wave numbers that must complete first */
  depends_on: number[];
  /** Wave-level strategy on failure */
  on_failure: "abort" | "continue" | "retry";
}

export interface PipelineStepDef {
  /** Step order within wave (for display) */
  order: number;
  /** Agent type to use */
  agent_type: string;
  /** Task description */
  description: string;
  /** Skills to load before this step */
  skills: string[];
  /** Crafted prompt for the agent */
  prompt: string;
  /** LLM model to use */
  model: string;
  /** Maximum turns for the agent */
  max_turns: number;
  /** Target files for scoping */
  target_files: string[];
  /** Target directories for scoping */
  target_directories: string[];
  /** Retry strategy on failure */
  retry_strategy: RetryStrategy;
  /** Max retries for this step */
  max_retries: number;
}

export interface PipelineConstraints {
  /** Max parallel agents per wave */
  max_parallel: number;
  /** Max total retries across pipeline */
  max_total_retries: number;
  /** Pipeline-level timeout in ms (0 = no limit) */
  timeout_ms: number;
}

// ============================================
// Pipeline Execution State (DB rows)
// ============================================

export interface PipelineRow {
  id: string;
  session_id: string;
  name: string | null;
  status: PipelineStatus;
  input: PipelineInput;
  plan: PipelinePlan | null;
  current_wave: number;
  config: PipelineConfig;
  synthesis: PipelineSynthesis | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
  updated_at: string;
}

export interface PipelineStepRow {
  id: string;
  pipeline_id: string;
  wave_number: number;
  step_order: number;
  agent_type: string;
  description: string | null;
  skills: string[] | null;
  prompt: string | null;
  model: string;
  max_turns: number;
  status: StepStatus;
  subtask_id: string | null;
  result: Record<string, unknown> | null;
  error: string | null;
  retry_count: number;
  retry_strategy: RetryStrategy;
  max_retries: number;
  started_at: string | null;
  completed_at: string | null;
  duration_ms: number | null;
  created_at: string;
}

export interface PipelineConfig {
  max_retries: number;
  strategy: "sequential" | "adaptive";
  parallel_limit: number;
}

// ============================================
// Pipeline Synthesis (final report)
// ============================================

export interface PipelineSynthesis {
  /** Human-readable summary */
  summary: string;
  /** Overall status */
  status: "success" | "partial" | "failed";
  /** Per-wave results */
  waves: WaveSynthesis[];
  /** Aggregated stats */
  stats: PipelineStats;
  /** Files modified across all steps */
  files_changed: string[];
  /** Errors encountered */
  errors: PipelineError[];
  /** Timeline of key events */
  timeline: TimelineEvent[];
}

export interface WaveSynthesis {
  wave_number: number;
  name: string;
  status: string;
  steps: StepSynthesis[];
  duration_ms: number;
}

export interface StepSynthesis {
  agent_type: string;
  description: string;
  status: StepStatus;
  result_summary: string | null;
  files_modified: string[];
  duration_ms: number;
  retries: number;
  error: string | null;
}

export interface PipelineStats {
  total_waves: number;
  total_steps: number;
  completed_steps: number;
  failed_steps: number;
  skipped_steps: number;
  total_retries: number;
  total_duration_ms: number;
  agents_used: string[];
  skills_loaded: string[];
}

export interface PipelineError {
  wave: number;
  step: number;
  agent_type: string;
  error: string;
  timestamp: string;
}

export interface TimelineEvent {
  timestamp: string;
  type: "pipeline_start" | "wave_start" | "wave_complete" | "step_start" | "step_complete" | "step_fail" | "retry" | "decision" | "pipeline_complete";
  wave?: number;
  step?: number;
  agent_type?: string;
  message: string;
}

// ============================================
// Decision Engine Types
// ============================================

export interface DecisionContext {
  pipeline: PipelineRow;
  current_wave: number;
  step: PipelineStepRow;
  error?: string;
  all_steps_in_wave: PipelineStepRow[];
  previous_wave_results: PipelineStepRow[];
}

export interface Decision {
  action: DecisionAction;
  reason: string;
  retry_strategy?: RetryStrategy;
  alternate_agent?: string;
  alternate_model?: string;
  injected_step?: PipelineStepDef;
}

// ============================================
// WebSocket Event Types
// ============================================

export interface PipelineEvent {
  pipeline_id: string;
  session_id: string;
  event: string;
  data: Record<string, unknown>;
  timestamp: number;
}
